from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


IST = "Asia/Kolkata"
UTC = "UTC"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build ML-ready trade candidates from aspect/SR touch rows. "
            "Each candidate is labelled as single_aspect or multiple_aspects, "
            "then evaluated with TP/SL/time-close rules."
        )
    )
    parser.add_argument(
        "--touch-log",
        default=r"C:\Users\ADMIN\Desktop\doc\sr_touch_full_1year_20260430_001906.csv",
        help="Touch CSV generated by sr_touch_lazy_dashboard.py or build_aspect_sr_touch_log.py.",
    )
    parser.add_argument(
        "--price",
        default=r"C:\Users\ADMIN\PycharmProjects\usd_jpy_h1_mt5_metaquotes_demo_full.parquet",
        help="OHLC parquet with a timezone-aware DatetimeIndex.",
    )
    parser.add_argument(
        "--output-csv",
        default=r"C:\Users\ADMIN\PycharmProjects\trade_candidates_aspect_sr_1y.csv",
        help="Output CSV path.",
    )
    parser.add_argument(
        "--output-parquet",
        default=r"C:\Users\ADMIN\PycharmProjects\trade_candidates_aspect_sr_1y.parquet",
        help="Output parquet path.",
    )
    parser.add_argument("--hold-hours", type=int, default=72)
    parser.add_argument("--tp-pct", type=float, default=0.30)
    parser.add_argument("--sl-pct", type=float, default=0.20)
    parser.add_argument(
        "--flat-pct",
        type=float,
        default=0.05,
        help="Absolute signed return below this percent is marked as low_movement for ML ignore analysis.",
    )
    return parser.parse_args()


def load_price(path: str) -> pd.DataFrame:
    price = pd.read_parquet(path).copy()
    if not isinstance(price.index, pd.DatetimeIndex):
        raise ValueError("Price parquet must have a DatetimeIndex.")
    if price.index.tz is None:
        price.index = price.index.tz_localize(UTC)
    else:
        price.index = price.index.tz_convert(UTC)
    required = {"open", "high", "low", "close"}
    missing = required - set(price.columns)
    if missing:
        raise ValueError(f"Price parquet missing columns: {sorted(missing)}")
    return price.sort_index()


def parse_event_aspect_count(value: Any) -> int:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return 0
    try:
        parsed = json.loads(str(value))
    except Exception:
        return 0
    if isinstance(parsed, list):
        return len(parsed)
    return 0


def normalize_touch_time(value: Any) -> pd.Timestamp | pd.NaT:
    ts = pd.to_datetime(value, errors="coerce")
    if pd.isna(ts):
        return pd.NaT
    if ts.tzinfo is None:
        ts = ts.tz_localize(IST)
    return ts.tz_convert(UTC)


def signal_direction(zone_kind: Any) -> str:
    zone = str(zone_kind or "").strip().lower()
    if zone == "bullish":
        return "LONG"
    if zone == "bearish":
        return "SHORT"
    return "NONE"


def signed_return_pct(direction: str, entry: float, close: float) -> float:
    if not np.isfinite(entry) or entry <= 0 or not np.isfinite(close):
        return np.nan
    raw = (float(close) - float(entry)) / float(entry) * 100.0
    if direction == "SHORT":
        return -raw
    if direction == "LONG":
        return raw
    return np.nan


def evaluate_exit(
    price: pd.DataFrame,
    entry_time: pd.Timestamp,
    direction: str,
    entry_price: float,
    hold_hours: int,
    tp_pct: float,
    sl_pct: float,
) -> dict[str, Any]:
    if direction not in {"LONG", "SHORT"}:
        return {"close_action": "IGNORE", "close_reason": "missing_direction"}
    if pd.isna(entry_time) or not np.isfinite(entry_price) or entry_price <= 0:
        return {"close_action": "IGNORE", "close_reason": "missing_entry"}

    end_time = entry_time + pd.Timedelta(hours=int(hold_hours))
    future = price[(price.index > entry_time) & (price.index <= end_time)].copy()
    if future.empty:
        return {"close_action": "IGNORE", "close_reason": "no_future_data"}

    entry = float(entry_price)
    tp = entry * (1.0 + tp_pct / 100.0) if direction == "LONG" else entry * (1.0 - tp_pct / 100.0)
    sl = entry * (1.0 - sl_pct / 100.0) if direction == "LONG" else entry * (1.0 + sl_pct / 100.0)

    max_high = float(future["high"].max())
    min_low = float(future["low"].min())
    final_close = float(future["close"].iloc[-1])
    final_time = future.index[-1]

    if direction == "LONG":
        mfe = (max_high - entry) / entry * 100.0
        mae = (entry - min_low) / entry * 100.0
    else:
        mfe = (entry - min_low) / entry * 100.0
        mae = (max_high - entry) / entry * 100.0

    for ts, row in future.iterrows():
        high = float(row["high"])
        low = float(row["low"])
        if direction == "LONG":
            hit_tp = high >= tp
            hit_sl = low <= sl
        else:
            hit_tp = low <= tp
            hit_sl = high >= sl

        if hit_sl and hit_tp:
            return {
                "close_action": "STOP_LOSS",
                "close_reason": "same_bar_tp_sl_conservative",
                "close_time_utc": ts,
                "close_price": sl,
                "signed_return_pct": -float(sl_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }
        if hit_sl:
            return {
                "close_action": "STOP_LOSS",
                "close_reason": "stop_loss_first",
                "close_time_utc": ts,
                "close_price": sl,
                "signed_return_pct": -float(sl_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }
        if hit_tp:
            return {
                "close_action": "TAKE_PROFIT",
                "close_reason": "take_profit_first",
                "close_time_utc": ts,
                "close_price": tp,
                "signed_return_pct": float(tp_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }

    return {
        "close_action": f"TIME_CLOSE_{int(hold_hours)}H",
        "close_reason": "hold_expired",
        "close_time_utc": final_time,
        "close_price": final_close,
        "signed_return_pct": signed_return_pct(direction, entry, final_close),
        "mfe_pct": float(mfe),
        "mae_pct": float(mae),
    }


def ignore_reason(row: pd.Series, flat_pct: float) -> str:
    if row.get("signal_direction") == "NONE":
        return "missing_direction"
    if str(row.get("close_action", "")).upper() == "IGNORE":
        return str(row.get("close_reason", "ignored"))
    signed_ret = row.get("signed_return_pct")
    if pd.notna(signed_ret) and abs(float(signed_ret)) < float(flat_pct):
        return "low_movement"
    return ""


def build_candidates(touches: pd.DataFrame, price: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    df = touches.copy()
    df["entry_time_utc"] = df["touch_time_local"].map(normalize_touch_time)
    df["entry_time_local"] = pd.to_datetime(df["touch_time_local"], errors="coerce")
    df["entry_price"] = pd.to_numeric(df.get("close_touch"), errors="coerce")
    df["signal_direction"] = df.get("zone_kind", "").map(signal_direction)

    active_count = pd.to_numeric(df.get("aspect_regime_active_count"), errors="coerce")
    event_json_count = df.get("event_aspects_json", pd.Series(index=df.index, dtype=object)).map(parse_event_aspect_count)
    df["active_aspect_count"] = active_count.fillna(event_json_count).fillna(0).astype(int)
    df["trade_category"] = np.where(df["active_aspect_count"] > 1, "multiple_aspects", "single_aspect")

    exits: list[dict[str, Any]] = []
    for row in df.itertuples(index=False):
        exits.append(
            evaluate_exit(
                price=price,
                entry_time=getattr(row, "entry_time_utc"),
                direction=getattr(row, "signal_direction"),
                entry_price=float(getattr(row, "entry_price")) if pd.notna(getattr(row, "entry_price")) else np.nan,
                hold_hours=args.hold_hours,
                tp_pct=args.tp_pct,
                sl_pct=args.sl_pct,
            )
        )
    exit_df = pd.DataFrame(exits)
    out = pd.concat([df.reset_index(drop=True), exit_df.reset_index(drop=True)], axis=1)

    out["ignore_reason"] = out.apply(lambda r: ignore_reason(r, args.flat_pct), axis=1)
    out["ignore_trade"] = (out["ignore_reason"].astype(str) != "").astype(int)
    out["potential_trade"] = (
        (out["signal_direction"].isin(["LONG", "SHORT"]))
        & (out["entry_price"].notna())
        & (out["entry_time_utc"].notna())
    ).astype(int)
    out["ml_outcome"] = np.select(
        [
            out["ignore_trade"].eq(1),
            out["signed_return_pct"].gt(0),
            out["signed_return_pct"].lt(0),
        ],
        ["IGNORE", "WIN", "LOSS"],
        default="FLAT",
    )
    return out


def main() -> None:
    args = parse_args()
    touches = pd.read_csv(args.touch_log)
    price = load_price(args.price)
    out = build_candidates(touches, price, args)

    output_csv = Path(args.output_csv)
    output_parquet = Path(args.output_parquet)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    output_parquet.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_csv, index=False)
    out.to_parquet(output_parquet, index=False)

    summary = {
        "rows": int(len(out)),
        "potential_trade": int(out["potential_trade"].sum()),
        "ignored": int(out["ignore_trade"].sum()),
        "trade_category_counts": out["trade_category"].value_counts(dropna=False).to_dict(),
        "close_action_counts": out["close_action"].value_counts(dropna=False).to_dict(),
        "ml_outcome_counts": out["ml_outcome"].value_counts(dropna=False).to_dict(),
        "output_csv": str(output_csv),
        "output_parquet": str(output_parquet),
    }
    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    main()
