from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from doctrine_config import append_doctrine_metadata

IST = "Asia/Kolkata"
UTC = "UTC"

HARD_ASPECTS = {"conjunction", "conjunction_orb", "square", "opposition", "opposition_orb"}
SOFT_ASPECTS = {"sextile", "trine"}
OUTER_OR_NODE_BODIES = {"RAHU", "KETU", "URANUS", "NEPTUNE", "PLUTO"}
FAST_BODIES = {"MOON", "MERCURY", "VENUS", "SUN", "MARS"}
AVG_ALL_LABEL = "AVG(ALL)"
AVG_ALL_CLASSICAL_SCORING_MEMBERS = ("SUN", "MOON", "MERCURY", "VENUS", "MARS", "JUPITER", "SATURN")
NATURAL_PLANET_BIAS = {
    "JUPITER": 1.0,
    "VENUS": 0.8,
    "MERCURY": 0.3,
    "MOON": 0.2,
    "SUN": -0.1,
    "MARS": -0.6,
    "SATURN": -0.8,
    "RAHU": -0.7,
    "KETU": -0.5,
    "URANUS": -0.4,
    "NEPTUNE": -0.4,
    "PLUTO": -0.6,
}
NATAL_HOUSE_BIAS = {
    1: 0.4,
    2: 0.9,
    3: 0.3,
    4: 0.2,
    5: 0.8,
    6: -0.5,
    7: 0.1,
    8: -1.0,
    9: 0.8,
    10: 0.7,
    11: 1.0,
    12: -0.9,
}
SIGN_ALIASES = {
    "AR": "ARIES",
    "ARIES": "ARIES",
    "MESHA": "ARIES",
    "TA": "TAURUS",
    "TAURUS": "TAURUS",
    "VRISHABHA": "TAURUS",
    "GE": "GEMINI",
    "GEMINI": "GEMINI",
    "MITHUNA": "GEMINI",
    "CN": "CANCER",
    "CANCER": "CANCER",
    "KARKATA": "CANCER",
    "LE": "LEO",
    "LEO": "LEO",
    "SIMHA": "LEO",
    "VI": "VIRGO",
    "VIRGO": "VIRGO",
    "KANYA": "VIRGO",
    "LI": "LIBRA",
    "LIBRA": "LIBRA",
    "TULA": "LIBRA",
    "THULA": "LIBRA",
    "SC": "SCORPIO",
    "SCORPIO": "SCORPIO",
    "VRISHCHIKA": "SCORPIO",
    "SG": "SAGITTARIUS",
    "SAGITTARIUS": "SAGITTARIUS",
    "DHANUS": "SAGITTARIUS",
    "CP": "CAPRICORN",
    "CAPRICORN": "CAPRICORN",
    "MAKARA": "CAPRICORN",
    "AQ": "AQUARIUS",
    "AQUARIUS": "AQUARIUS",
    "KUMBHA": "AQUARIUS",
    "PI": "PISCES",
    "PISCES": "PISCES",
    "MEENA": "PISCES",
}
SIGN_LORDS = {
    "ARIES": "MARS",
    "TAURUS": "VENUS",
    "GEMINI": "MERCURY",
    "CANCER": "MOON",
    "LEO": "SUN",
    "VIRGO": "MERCURY",
    "LIBRA": "VENUS",
    "SCORPIO": "MARS",
    "SAGITTARIUS": "JUPITER",
    "CAPRICORN": "SATURN",
    "AQUARIUS": "SATURN",
    "PISCES": "JUPITER",
}
OWN_SIGNS = {
    "SUN": {"LEO"},
    "MOON": {"CANCER"},
    "MARS": {"ARIES", "SCORPIO"},
    "MERCURY": {"GEMINI", "VIRGO"},
    "JUPITER": {"SAGITTARIUS", "PISCES"},
    "VENUS": {"TAURUS", "LIBRA"},
    "SATURN": {"CAPRICORN", "AQUARIUS"},
}
EXALTATION_SIGNS = {
    "SUN": "ARIES",
    "MOON": "TAURUS",
    "MARS": "CAPRICORN",
    "MERCURY": "VIRGO",
    "JUPITER": "CANCER",
    "VENUS": "PISCES",
    "SATURN": "LIBRA",
}
DEBILITATION_SIGNS = {
    "SUN": "LIBRA",
    "MOON": "SCORPIO",
    "MARS": "CANCER",
    "MERCURY": "PISCES",
    "JUPITER": "CAPRICORN",
    "VENUS": "VIRGO",
    "SATURN": "ARIES",
}
MOOLATRIKONA_SIGNS = {
    "SUN": "LEO",
    "MOON": "TAURUS",
    "MARS": "ARIES",
    "MERCURY": "VIRGO",
    "JUPITER": "SAGITTARIUS",
    "VENUS": "LIBRA",
    "SATURN": "AQUARIUS",
}
NATURAL_RELATIONSHIPS = {
    "SUN": {"friend": {"MOON", "MARS", "JUPITER"}, "neutral": {"MERCURY"}, "enemy": {"VENUS", "SATURN"}},
    "MOON": {"friend": {"SUN", "MERCURY"}, "neutral": {"MARS", "JUPITER", "VENUS", "SATURN"}, "enemy": set()},
    "MARS": {"friend": {"SUN", "MOON", "JUPITER"}, "neutral": {"VENUS", "SATURN"}, "enemy": {"MERCURY"}},
    "MERCURY": {"friend": {"SUN", "VENUS"}, "neutral": {"MARS", "JUPITER", "SATURN"}, "enemy": {"MOON"}},
    "JUPITER": {"friend": {"SUN", "MOON", "MARS"}, "neutral": {"SATURN"}, "enemy": {"MERCURY", "VENUS"}},
    "VENUS": {"friend": {"MERCURY", "SATURN"}, "neutral": {"MARS", "JUPITER"}, "enemy": {"SUN", "MOON"}},
    "SATURN": {"friend": {"MERCURY", "VENUS"}, "neutral": {"JUPITER"}, "enemy": {"SUN", "MOON", "MARS"}},
}
STHANA_VIRUPA_BY_DIGNITY = {
    "exaltation": 60.0,
    "moolatrikona": 45.0,
    "own": 30.0,
    "friend": 15.0,
    "neutral": 10.0,
    "enemy": 4.0,
    "debilitation": 0.0,
    "unknown": 0.0,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build ML-ready trade candidates from aspect/SR touch rows. "
            "Each candidate is labelled as single_aspect or multiple_aspects, "
            "then evaluated with TP/SL/time-close rules."
        )
    )
    parser.add_argument(
        "--touch-log",
        default=r"D:\GannFinancialAstro\doc\sr_touch_full_1year_20260430_001906.csv",
        help="Touch CSV generated by sr_touch_lazy_dashboard.py or build_aspect_sr_touch_log.py.",
    )
    parser.add_argument(
        "--price",
        default=r"D:\PycharmProjects\usd_jpy_h1_mt5_metaquotes_demo_full.parquet",
        help="OHLC parquet with a timezone-aware DatetimeIndex.",
    )
    parser.add_argument(
        "--output-csv",
        default=r"D:\PycharmProjects\trade_candidates_aspect_sr_1y.csv",
        help="Output CSV path.",
    )
    parser.add_argument(
        "--output-parquet",
        default=r"D:\PycharmProjects\trade_candidates_aspect_sr_1y.parquet",
        help="Output parquet path.",
    )
    parser.add_argument("--hold-hours", type=int, default=72)
    parser.add_argument("--tp-pct", type=float, default=0.30)
    parser.add_argument("--sl-pct", type=float, default=0.20)
    parser.add_argument(
        "--flat-pct",
        type=float,
        default=0.05,
        help="Absolute signed return below this percent is marked as low_movement for ML ignore analysis.",
    )
    return parser.parse_args()


def load_price(path: str) -> pd.DataFrame:
    price = pd.read_parquet(path).copy()
    if not isinstance(price.index, pd.DatetimeIndex):
        raise ValueError("Price parquet must have a DatetimeIndex.")
    if price.index.tz is None:
        price.index = price.index.tz_localize(UTC)
    else:
        price.index = price.index.tz_convert(UTC)
    required = {"open", "high", "low", "close"}
    missing = required - set(price.columns)
    if missing:
        raise ValueError(f"Price parquet missing columns: {sorted(missing)}")
    return price.sort_index()


def parse_event_aspect_count(value: Any) -> int:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return 0
    try:
        parsed = json.loads(str(value))
    except Exception:
        return 0
    if isinstance(parsed, list):
        return len(parsed)
    return 0


def safe_json_list(value: Any) -> list[dict[str, Any]]:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return []
    try:
        parsed = json.loads(str(value))
    except Exception:
        return []
    if not isinstance(parsed, list):
        return []
    return [item for item in parsed if isinstance(item, dict)]


def numeric_series(df: pd.DataFrame, col: str, default: float = 0.0) -> pd.Series:
    if col not in df.columns:
        return pd.Series(default, index=df.index, dtype=float)
    return pd.to_numeric(df[col], errors="coerce").fillna(default)


def normalize_body(value: Any) -> str:
    return str(value or "").strip().upper()


def normalize_sign(value: Any) -> str:
    text = str(value or "").strip().upper().replace("-", " ").replace("_", " ")
    text = " ".join(text.split())
    return SIGN_ALIASES.get(text, text)


def aspect_family(aspect: Any) -> str:
    name = str(aspect or "").strip().lower()
    if name in HARD_ASPECTS or name.startswith("rashi_"):
        return "hard"
    if name in SOFT_ASPECTS:
        return "soft"
    return "other"


def comparable_aspect_name(aspect: Any) -> str:
    name = str(aspect or "").strip().lower()
    if name.endswith("_orb"):
        name = name[: -len("_orb")]
    return name


def pair_bodies(pair_key: Any) -> set[str]:
    text = str(pair_key or "").strip()
    if not text:
        return set()
    return {normalize_body(part) for part in text.split("|") if str(part).strip()}


def expand_scoring_bodies(bodies: set[str] | None) -> set[str]:
    expanded: set[str] = set()
    for body in bodies or set():
        normalized = normalize_body(body)
        if not normalized:
            continue
        if normalized == AVG_ALL_LABEL:
            expanded.update(AVG_ALL_CLASSICAL_SCORING_MEMBERS)
        else:
            expanded.add(normalized)
    return expanded


def duration_bucket(minutes: Any) -> str:
    try:
        value = float(minutes)
    except Exception:
        return "unknown"
    if not np.isfinite(value):
        return "unknown"
    if value <= 24.0 * 60.0:
        return "trigger_le_1d"
    if value <= 5.0 * 24.0 * 60.0:
        return "swing_1d_to_5d"
    return "position_gt_5d"


def body_bias(body: Any) -> float:
    return float(NATURAL_PLANET_BIAS.get(normalize_body(body), 0.0))


def house_bias(house: Any) -> float:
    try:
        key = int(float(house))
    except Exception:
        return 0.0
    return float(NATAL_HOUSE_BIAS.get(key, 0.0))


def dignity_for_planet_in_sign(planet: Any, sign: Any) -> dict[str, Any]:
    body = normalize_body(planet)
    sign_name = normalize_sign(sign)
    if body not in OWN_SIGNS or sign_name not in SIGN_LORDS:
        return {
            "dignity_label": "unknown",
            "dignity_virupa": 0.0,
            "sign_lord": SIGN_LORDS.get(sign_name, ""),
            "sign_relation": "unknown",
        }
    if sign_name == DEBILITATION_SIGNS.get(body):
        label = "debilitation"
        relation = "enemy"
    elif sign_name == EXALTATION_SIGNS.get(body):
        label = "exaltation"
        relation = "friend"
    elif sign_name == MOOLATRIKONA_SIGNS.get(body):
        label = "moolatrikona"
        relation = "own"
    elif sign_name in OWN_SIGNS.get(body, set()):
        label = "own"
        relation = "own"
    else:
        lord = SIGN_LORDS.get(sign_name, "")
        relationships = NATURAL_RELATIONSHIPS.get(body, {})
        if lord in relationships.get("friend", set()):
            label = "friend"
            relation = "friend"
        elif lord in relationships.get("enemy", set()):
            label = "enemy"
            relation = "enemy"
        else:
            label = "neutral"
            relation = "neutral"
    return {
        "dignity_label": label,
        "dignity_virupa": float(STHANA_VIRUPA_BY_DIGNITY[label]),
        "sign_lord": SIGN_LORDS.get(sign_name, ""),
        "sign_relation": relation,
    }


def hit_dignity_context(hit: dict[str, Any]) -> dict[str, Any]:
    natal = dignity_for_planet_in_sign(hit.get("natal_planet"), hit.get("natal_sign"))
    transit = dignity_for_planet_in_sign(hit.get("transit_planet"), hit.get("transit_sign"))
    virupas = [float(natal["dignity_virupa"])]
    if str(hit.get("transit_sign", "")).strip():
        virupas.append(float(transit["dignity_virupa"]))
    avg_virupa = float(np.mean(virupas)) if virupas else 0.0
    return {
        "natal_dignity_label": str(natal["dignity_label"]),
        "natal_dignity_virupa": float(natal["dignity_virupa"]),
        "natal_sign_lord": str(natal["sign_lord"]),
        "natal_sign_relation": str(natal["sign_relation"]),
        "transit_dignity_label": str(transit["dignity_label"]),
        "transit_dignity_virupa": float(transit["dignity_virupa"]),
        "transit_sign_lord": str(transit["sign_lord"]),
        "transit_sign_relation": str(transit["sign_relation"]),
        "avg_dignity_virupa": avg_virupa,
        "strength_factor": 0.5 + avg_virupa / 60.0,
    }


def aspect_family_bias(aspect: Any) -> float:
    family = aspect_family(aspect)
    if family == "soft":
        return 0.25
    if family == "hard":
        return -0.25
    return 0.0


def hit_strength(hit: dict[str, Any]) -> float:
    for key in ("bphs_strength", "score"):
        try:
            value = float(hit.get(key))
        except Exception:
            continue
        if np.isfinite(value):
            return max(0.0, value)
    return 0.0


def score_transit_natal_hits(
    value: Any,
    event_aspect: Any = None,
    event_bodies: set[str] | None = None,
) -> dict[str, Any]:
    hits = safe_json_list(value)
    bodies = expand_scoring_bodies(event_bodies)
    aspect_name = comparable_aspect_name(event_aspect)
    if bodies:
        body_hits = [hit for hit in hits if normalize_body(hit.get("transit_planet")) in bodies]
        aspect_hits = [
            hit for hit in body_hits
            if aspect_name and comparable_aspect_name(hit.get("aspect")) == aspect_name
        ]
        hits = aspect_hits or body_hits

    bullish = 0.0
    bearish = 0.0
    strongest_id = ""
    strongest_signed = 0.0
    strongest_abs = 0.0
    doctrine_bullish = 0.0
    doctrine_bearish = 0.0
    doctrine_strongest_id = ""
    doctrine_strongest_signed = 0.0
    doctrine_strongest_abs = 0.0
    doctrine_strongest_dignity = ""
    dignity_virupa_weighted = 0.0
    dignity_weight = 0.0
    scored_hits = 0

    for hit in hits:
        strength = hit_strength(hit)
        if strength <= 0:
            continue
        scored_hits += 1
        dignity = hit_dignity_context(hit)
        directional_bias = (
            house_bias(hit.get("natal_house"))
            + 0.50 * body_bias(hit.get("natal_planet"))
            + 0.25 * body_bias(hit.get("transit_planet"))
            + aspect_family_bias(hit.get("aspect"))
        )
        signed = strength * directional_bias
        doctrine_signed = signed * float(dignity["strength_factor"])
        if signed >= 0:
            bullish += signed
        else:
            bearish += abs(signed)
        if doctrine_signed >= 0:
            doctrine_bullish += doctrine_signed
        else:
            doctrine_bearish += abs(doctrine_signed)
        dignity_virupa_weighted += strength * float(dignity["avg_dignity_virupa"])
        dignity_weight += strength
        hit_id = (
            f"{normalize_body(hit.get('transit_planet'))}>"
            f"{normalize_body(hit.get('natal_planet'))}:"
            f"{str(hit.get('aspect', '')).strip().lower()}"
        )
        if abs(signed) > strongest_abs:
            strongest_abs = abs(signed)
            strongest_signed = signed
            strongest_id = hit_id
        if abs(doctrine_signed) > doctrine_strongest_abs:
            doctrine_strongest_abs = abs(doctrine_signed)
            doctrine_strongest_signed = doctrine_signed
            doctrine_strongest_id = hit_id
            doctrine_strongest_dignity = (
                f"natal {dignity['natal_dignity_label']} "
                f"{dignity['natal_dignity_virupa']:.0f}V"
                + (
                    f"; transit {dignity['transit_dignity_label']} "
                    f"{dignity['transit_dignity_virupa']:.0f}V"
                    if str(hit.get("transit_sign", "")).strip()
                    else ""
                )
            )

    net = bullish - bearish
    conflict = min(bullish, bearish)
    doctrine_net = doctrine_bullish - doctrine_bearish
    doctrine_conflict = min(doctrine_bullish, doctrine_bearish)
    dignity_avg = dignity_virupa_weighted / dignity_weight if dignity_weight > 0 else 0.0
    if scored_hits <= 0:
        direction = "UNKNOWN"
        doctrine_direction = "UNKNOWN"
    elif bullish > bearish * 1.25:
        direction = "BULLISH"
    else:
        direction = "BEARISH" if bearish > bullish * 1.25 else "CONFLICT"
    if scored_hits > 0:
        if doctrine_bullish > doctrine_bearish * 1.25:
            doctrine_direction = "BULLISH"
        elif doctrine_bearish > doctrine_bullish * 1.25:
            doctrine_direction = "BEARISH"
        else:
            doctrine_direction = "CONFLICT"

    return {
        "jyotish_bullish_score": float(bullish),
        "jyotish_bearish_score": float(bearish),
        "jyotish_net_score": float(net),
        "jyotish_conflict_score": float(conflict),
        "jyotish_hypothesis_direction": direction,
        "jyotish_scored_hit_count": int(scored_hits),
        "dominant_aspect_id": strongest_id,
        "dominant_aspect_signed_score": float(strongest_signed),
        "dominant_aspect_abs_score": float(strongest_abs),
        "doctrine_bullish_score": float(doctrine_bullish),
        "doctrine_bearish_score": float(doctrine_bearish),
        "doctrine_net_score": float(doctrine_net),
        "doctrine_conflict_score": float(doctrine_conflict),
        "doctrine_hypothesis_direction": doctrine_direction,
        "doctrine_dignity_virupa_avg": float(dignity_avg),
        "doctrine_dignity_strength_factor_avg": float(0.5 + dignity_avg / 60.0),
        "doctrine_dominant_aspect_id": doctrine_strongest_id,
        "doctrine_dominant_aspect_signed_score": float(doctrine_strongest_signed),
        "doctrine_dominant_aspect_abs_score": float(doctrine_strongest_abs),
        "doctrine_dominant_dignity": doctrine_strongest_dignity,
    }


def score_transit_natal_hits_for_row(row: pd.Series) -> dict[str, Any]:
    return score_transit_natal_hits(
        row.get("tn_hits_json"),
        event_aspect=row.get("aspect"),
        event_bodies=pair_bodies(row.get("pair_key")),
    )


def prefixed_score(data: dict[str, Any], prefix: str) -> dict[str, Any]:
    return {f"{prefix}{key}": value for key, value in data.items()}


def direction_from_net_score(net: float, conflict_ratio: float = 0.0) -> str:
    if not np.isfinite(net):
        return "UNKNOWN"
    if abs(net) <= 0.05:
        return "CONFLICT"
    if conflict_ratio >= 0.45:
        return "CONFLICT"
    return "BULLISH" if net > 0 else "BEARISH"


def has_nonempty_value(value: Any) -> bool:
    if value is None:
        return False
    if isinstance(value, str):
        return value.strip().lower() not in {"", "nan", "none", "nat"}
    try:
        return bool(pd.notna(value))
    except Exception:
        return True


def finite_number(value: Any, default: float = np.nan) -> float:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return float(default)
    return number if np.isfinite(number) else float(default)


def score_currency_pair_for_row(row: pd.Series) -> dict[str, Any]:
    event_aspect = row.get("aspect")
    bodies = pair_bodies(row.get("pair_key"))
    base_hits_raw = row.get("base_tn_hits_json")
    has_base_reference = has_nonempty_value(base_hits_raw)
    has_padmanabhan_evidence = has_nonempty_value(row.get("event_padmanabhan_pair_prosperity_index_i"))
    quote = score_transit_natal_hits(
        row.get("tn_hits_json"),
        event_aspect=event_aspect,
        event_bodies=bodies,
    )
    base = score_transit_natal_hits(
        row.get("base_tn_hits_json"),
        event_aspect=event_aspect,
        event_bodies=bodies,
    )

    base_net = float(base["jyotish_net_score"])
    quote_net = float(quote["jyotish_net_score"])
    pair_net = base_net - quote_net if has_base_reference else 0.0
    doctrine_base_net = float(base["doctrine_net_score"])
    doctrine_quote_net = float(quote["doctrine_net_score"])
    doctrine_pair_net = doctrine_base_net - doctrine_quote_net if has_base_reference else 0.0
    base_total = float(base["jyotish_bullish_score"]) + float(base["jyotish_bearish_score"])
    quote_total = float(quote["jyotish_bullish_score"]) + float(quote["jyotish_bearish_score"])
    conflict = float(base["jyotish_conflict_score"]) + float(quote["jyotish_conflict_score"])
    total_directional = base_total + quote_total
    conflict_ratio = conflict / total_directional if has_base_reference and total_directional > 0 else 0.0
    doctrine_base_total = float(base["doctrine_bullish_score"]) + float(base["doctrine_bearish_score"])
    doctrine_quote_total = float(quote["doctrine_bullish_score"]) + float(quote["doctrine_bearish_score"])
    doctrine_conflict = float(base["doctrine_conflict_score"]) + float(quote["doctrine_conflict_score"])
    doctrine_total_directional = doctrine_base_total + doctrine_quote_total
    doctrine_conflict_ratio = (
        doctrine_conflict / doctrine_total_directional
        if has_base_reference and doctrine_total_directional > 0
        else 0.0
    )
    direction = (
        "UNKNOWN"
        if not has_base_reference
        or (int(base["jyotish_scored_hit_count"]) <= 0 and int(quote["jyotish_scored_hit_count"]) <= 0)
        else direction_from_net_score(pair_net, conflict_ratio)
    )
    doctrine_direction = (
        "UNKNOWN"
        if not has_base_reference
        or (int(base["jyotish_scored_hit_count"]) <= 0 and int(quote["jyotish_scored_hit_count"]) <= 0)
        else direction_from_net_score(doctrine_pair_net, doctrine_conflict_ratio)
    )

    out = {
        "fx_base_reference_label": str(row.get("base_reference_label", "USD") or "USD"),
        "fx_quote_reference_label": str(row.get("quote_reference_label", "JPY") or "JPY"),
        "fx_base_net_score": base_net,
        "fx_quote_net_score": quote_net,
        "fx_pair_net_score": float(pair_net),
        "fx_pair_conflict_score": float(conflict),
        "fx_pair_conflict_ratio": float(conflict_ratio),
        "fx_hypothesis_direction": direction,
        "fx_doctrine_base_net_score": doctrine_base_net,
        "fx_doctrine_quote_net_score": doctrine_quote_net,
        "fx_doctrine_pair_net_score": float(doctrine_pair_net),
        "fx_doctrine_pair_conflict_score": float(doctrine_conflict),
        "fx_doctrine_pair_conflict_ratio": float(doctrine_conflict_ratio),
        "fx_doctrine_hypothesis_direction": doctrine_direction,
        "fx_doctrine_base_dignity_virupa_avg": float(base["doctrine_dignity_virupa_avg"]),
        "fx_doctrine_quote_dignity_virupa_avg": float(quote["doctrine_dignity_virupa_avg"]),
        "fx_base_scored_hit_count": int(base["jyotish_scored_hit_count"]),
        "fx_quote_scored_hit_count": int(quote["jyotish_scored_hit_count"]),
        "fx_dominant_base_hit": str(base["dominant_aspect_id"]),
        "fx_dominant_quote_hit": str(quote["dominant_aspect_id"]),
        "fx_doctrine_dominant_base_hit": str(base["doctrine_dominant_aspect_id"]),
        "fx_doctrine_dominant_quote_hit": str(quote["doctrine_dominant_aspect_id"]),
        "fx_doctrine_dominant_base_dignity": str(base["doctrine_dominant_dignity"]),
        "fx_doctrine_dominant_quote_dignity": str(quote["doctrine_dominant_dignity"]),
        "fx_padmanabhan_base_prosperity_index": finite_number(
            row.get("event_padmanabhan_base_prosperity_index_i")
        ),
        "fx_padmanabhan_quote_prosperity_index": finite_number(
            row.get("event_padmanabhan_quote_prosperity_index_i")
        ),
        "fx_padmanabhan_pair_prosperity_index": finite_number(
            row.get("event_padmanabhan_pair_prosperity_index_i")
        ),
        "fx_padmanabhan_pair_direction": str(row.get("event_padmanabhan_pair_direction", "") or ""),
        "fx_padmanabhan_rule_id": str(row.get("event_padmanabhan_timing_rule_id", "") or ""),
        "fx_padmanabhan_status": str(row.get("event_padmanabhan_timing_status", "") or ""),
        "fx_padmanabhan_evidence_only": int(has_padmanabhan_evidence),
        "fx_scoring_notes": (
            "heuristic_v1_base_minus_quote;USDJPY=USD_reference_score-JPY_reference_score;"
            "doctrine_v1_adds_sign_dignity_friendship_sthana_bala;"
            "padmanabhan_timing_index_is_parallel_evidence_only_not_signal_input;"
            "full_shadbala_and_strict_drik_bala_pending;ml_must_validate"
            ";avg_all_scoring_expands_to_7_classical_planets"
            if has_base_reference
            else "base_reference_missing;pair_hypothesis_not_scored"
        ),
    }
    out.update(prefixed_score(base, "base_"))
    out.update(prefixed_score(quote, "quote_"))
    return out


def aspect_stats_from_event_json(value: Any) -> dict[str, Any]:
    aspects = safe_json_list(value)
    hard = 0
    soft = 0
    has_moon = False
    has_outer_or_node = False
    max_duration = 0.0
    for item in aspects:
        family = aspect_family(item.get("aspect"))
        hard += int(family == "hard")
        soft += int(family == "soft")
        bodies = [normalize_body(b) for b in item.get("bodies", []) if str(b or "").strip()]
        has_moon = has_moon or ("MOON" in bodies)
        has_outer_or_node = has_outer_or_node or any(body in OUTER_OR_NODE_BODIES for body in bodies)
        try:
            dur = float(item.get("duration_min"))
        except Exception:
            dur = 0.0
        if np.isfinite(dur):
            max_duration = max(max_duration, dur)

    return {
        "active_hard_aspect_count": int(hard),
        "active_soft_aspect_count": int(soft),
        "has_mixed_hard_soft_aspects": int(hard > 0 and soft > 0),
        "event_json_has_moon": int(has_moon),
        "event_json_has_outer_or_node": int(has_outer_or_node),
        "event_json_max_duration_minutes": float(max_duration),
    }


def normalize_touch_time(value: Any) -> pd.Timestamp | pd.NaT:
    ts = pd.to_datetime(value, errors="coerce")
    if pd.isna(ts):
        return pd.NaT
    if ts.tzinfo is None:
        ts = ts.tz_localize(IST)
    return ts.tz_convert(UTC)


def signal_direction(zone_kind: Any) -> str:
    zone = str(zone_kind or "").strip().lower()
    if zone == "bullish":
        return "LONG"
    if zone == "bearish":
        return "SHORT"
    return "NONE"


def signed_return_pct(direction: str, entry: float, close: float) -> float:
    if not np.isfinite(entry) or entry <= 0 or not np.isfinite(close):
        return np.nan
    raw = (float(close) - float(entry)) / float(entry) * 100.0
    if direction == "SHORT":
        return -raw
    if direction == "LONG":
        return raw
    return np.nan


def ignored_exit(reason: str) -> dict[str, Any]:
    return {
        "close_action": "IGNORE",
        "close_reason": str(reason),
        "close_time_utc": pd.NaT,
        "close_price": np.nan,
        "signed_return_pct": np.nan,
        "mfe_pct": np.nan,
        "mae_pct": np.nan,
    }


def evaluate_exit(
    price: pd.DataFrame,
    entry_time: pd.Timestamp,
    direction: str,
    entry_price: float,
    hold_hours: int,
    tp_pct: float,
    sl_pct: float,
) -> dict[str, Any]:
    if direction not in {"LONG", "SHORT"}:
        return ignored_exit("missing_direction")
    if pd.isna(entry_time) or not np.isfinite(entry_price) or entry_price <= 0:
        return ignored_exit("missing_entry")

    end_time = entry_time + pd.Timedelta(hours=int(hold_hours))
    future = price[(price.index > entry_time) & (price.index <= end_time)].copy()
    if future.empty:
        return ignored_exit("no_future_data")

    entry = float(entry_price)
    tp = entry * (1.0 + tp_pct / 100.0) if direction == "LONG" else entry * (1.0 - tp_pct / 100.0)
    sl = entry * (1.0 - sl_pct / 100.0) if direction == "LONG" else entry * (1.0 + sl_pct / 100.0)

    max_high = float(future["high"].max())
    min_low = float(future["low"].min())
    final_close = float(future["close"].iloc[-1])
    final_time = future.index[-1]

    if direction == "LONG":
        mfe = (max_high - entry) / entry * 100.0
        mae = (entry - min_low) / entry * 100.0
    else:
        mfe = (entry - min_low) / entry * 100.0
        mae = (max_high - entry) / entry * 100.0

    for ts, row in future.iterrows():
        high = float(row["high"])
        low = float(row["low"])
        if direction == "LONG":
            hit_tp = high >= tp
            hit_sl = low <= sl
        else:
            hit_tp = low <= tp
            hit_sl = high >= sl

        if hit_sl and hit_tp:
            return {
                "close_action": "STOP_LOSS",
                "close_reason": "same_bar_tp_sl_conservative",
                "close_time_utc": ts,
                "close_price": sl,
                "signed_return_pct": -float(sl_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }
        if hit_sl:
            return {
                "close_action": "STOP_LOSS",
                "close_reason": "stop_loss_first",
                "close_time_utc": ts,
                "close_price": sl,
                "signed_return_pct": -float(sl_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }
        if hit_tp:
            return {
                "close_action": "TAKE_PROFIT",
                "close_reason": "take_profit_first",
                "close_time_utc": ts,
                "close_price": tp,
                "signed_return_pct": float(tp_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }

    return {
        "close_action": f"TIME_CLOSE_{int(hold_hours)}H",
        "close_reason": "hold_expired",
        "close_time_utc": final_time,
        "close_price": final_close,
        "signed_return_pct": signed_return_pct(direction, entry, final_close),
        "mfe_pct": float(mfe),
        "mae_pct": float(mae),
    }


def ignore_reason(row: pd.Series, flat_pct: float) -> str:
    if row.get("signal_direction") == "NONE":
        return "missing_direction"
    if str(row.get("close_action", "")).upper() == "IGNORE":
        return str(row.get("close_reason", "ignored"))
    signed_ret = row.get("signed_return_pct")
    if pd.notna(signed_ret) and abs(float(signed_ret)) < float(flat_pct):
        return "low_movement"
    return ""


def build_candidates(touches: pd.DataFrame, price: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    df = touches.copy()
    empty_text = pd.Series("", index=df.index, dtype=object)
    df["entry_time_utc"] = df["touch_time_local"].map(normalize_touch_time)
    df["entry_time_local"] = pd.to_datetime(df["touch_time_local"], errors="coerce")
    df["entry_price"] = pd.to_numeric(df.get("close_touch"), errors="coerce")
    df["signal_direction"] = df.get("zone_kind", empty_text).map(signal_direction)
    df["aspect_family"] = df.get("aspect", empty_text).map(aspect_family)
    df["duration_bucket"] = df.get("event_duration_minutes", pd.Series(index=df.index, dtype=object)).map(duration_bucket)
    df["sr_confirmation_type"] = df.get("touch_kind", empty_text).fillna("").astype(str)
    df["sr_confirmation_score"] = df["sr_confirmation_type"].map({"confluence": 1.0, "nearest_line": 0.6}).fillna(0.0)

    active_count = pd.to_numeric(df.get("aspect_regime_active_count"), errors="coerce")
    event_json_count = df.get("event_aspects_json", pd.Series(index=df.index, dtype=object)).map(parse_event_aspect_count)
    df["active_aspect_count"] = active_count.fillna(event_json_count).fillna(0).astype(int)
    df["trade_category"] = np.where(df["active_aspect_count"] > 1, "multiple_aspects", "single_aspect")
    df["is_multiple_active"] = (df["active_aspect_count"] > 1).astype(int)
    df["has_moon_trigger"] = pd.to_numeric(df.get("touch_has_moon"), errors="coerce").fillna(0).astype(int)
    touch_planets_text = df.get("touch_planets", pd.Series(index=df.index, dtype=object)).fillna("").astype(str).str.upper()
    pair_text = df.get("pair_key", pd.Series(index=df.index, dtype=object)).fillna("").astype(str).str.upper()
    df["has_outer_or_node"] = (
        touch_planets_text.apply(lambda text: any(body in text for body in OUTER_OR_NODE_BODIES))
        | pair_text.apply(lambda text: any(body in text for body in OUTER_OR_NODE_BODIES))
    ).astype(int)

    aspect_stats = pd.DataFrame(
        df.get("event_aspects_json", pd.Series(index=df.index, dtype=object)).map(aspect_stats_from_event_json).tolist()
    )
    if not aspect_stats.empty:
        df = df.drop(columns=[col for col in aspect_stats.columns if col in df.columns], errors="ignore")
        df = pd.concat([df.reset_index(drop=True), aspect_stats.reset_index(drop=True)], axis=1)
        df["has_moon_trigger"] = np.maximum(df["has_moon_trigger"], df["event_json_has_moon"].fillna(0).astype(int))
        df["has_outer_or_node"] = np.maximum(df["has_outer_or_node"], df["event_json_has_outer_or_node"].fillna(0).astype(int))

    scored = pd.DataFrame(df.apply(score_transit_natal_hits_for_row, axis=1).tolist())
    if not scored.empty:
        df = df.drop(columns=[col for col in scored.columns if col in df.columns], errors="ignore")
        df = pd.concat([df.reset_index(drop=True), scored.reset_index(drop=True)], axis=1)
    else:
        for col in (
            "jyotish_bullish_score",
            "jyotish_bearish_score",
            "jyotish_net_score",
            "jyotish_conflict_score",
            "jyotish_scored_hit_count",
            "dominant_aspect_signed_score",
            "dominant_aspect_abs_score",
            "doctrine_bullish_score",
            "doctrine_bearish_score",
            "doctrine_net_score",
            "doctrine_conflict_score",
            "doctrine_dignity_virupa_avg",
            "doctrine_dignity_strength_factor_avg",
            "doctrine_dominant_aspect_signed_score",
            "doctrine_dominant_aspect_abs_score",
        ):
            df[col] = 0.0
        df["jyotish_hypothesis_direction"] = "UNKNOWN"
        df["dominant_aspect_id"] = ""
        df["doctrine_hypothesis_direction"] = "UNKNOWN"
        df["doctrine_dominant_aspect_id"] = ""
        df["doctrine_dominant_dignity"] = ""

    fx_scored = pd.DataFrame(df.apply(score_currency_pair_for_row, axis=1).tolist())
    if not fx_scored.empty:
        df = df.drop(columns=[col for col in fx_scored.columns if col in df.columns], errors="ignore")
        df = pd.concat([df.reset_index(drop=True), fx_scored.reset_index(drop=True)], axis=1)
    else:
        df["fx_hypothesis_direction"] = "UNKNOWN"
        df["fx_pair_net_score"] = 0.0
        df["fx_pair_conflict_score"] = 0.0
        df["fx_pair_conflict_ratio"] = 0.0
        df["fx_doctrine_hypothesis_direction"] = "UNKNOWN"
        df["fx_doctrine_pair_net_score"] = 0.0
        df["fx_doctrine_pair_conflict_score"] = 0.0
        df["fx_doctrine_pair_conflict_ratio"] = 0.0

    df = append_doctrine_metadata(df)
    event_strength = numeric_series(df, "event_bphs_like_orb_strength")
    natal_strength = numeric_series(df, "tn_bphs_total")
    df["geometric_strength_score"] = event_strength
    df["natal_relevance_score"] = natal_strength
    df["rule_layer_total_strength"] = (
        numeric_series(df, "dominant_aspect_abs_score")
        + 0.35 * event_strength
        + 0.25 * numeric_series(df, "sr_confirmation_score")
    )
    df["fx_rule_layer_total_strength"] = (
        numeric_series(df, "fx_pair_net_score").abs()
        + 0.35 * event_strength
        + 0.25 * numeric_series(df, "sr_confirmation_score")
    )
    df["fx_doctrine_rule_layer_total_strength"] = (
        numeric_series(df, "fx_doctrine_pair_net_score").abs()
        + 0.35 * event_strength
        + 0.25 * numeric_series(df, "sr_confirmation_score")
    )
    directional_total = numeric_series(df, "jyotish_bullish_score") + numeric_series(df, "jyotish_bearish_score")
    df["rule_layer_conflict_ratio"] = np.where(
        directional_total > 0,
        numeric_series(df, "jyotish_conflict_score") / directional_total,
        0.0,
    )
    df["rule_layer_ignore_hint"] = np.where(
        df["jyotish_hypothesis_direction"].isin(["CONFLICT", "UNKNOWN"]) | (df["rule_layer_total_strength"] < 0.25),
        1,
        0,
    )
    df["rule_layer_notes"] = (
        "heuristic_v1_yen_ipo_tokyo_1889_reference;"
        "uses_transit_natal_house_planet_nature_aspect_family_bphs_like_orb_proxy_sr;"
        "fx_pair_score_is_base_minus_quote_when_base_reference_fields_exist;"
        "doctrine_v1_uses_sign_dignity_friendship_sthana_bala_for_classical_planets;"
        "padmanabhan_timing_v1_is_source_bounded_evidence_only_and_does_not_change_trade_direction;"
        "full_shadbala_and_strict_drik_bala_pending;"
        "ml_must_validate"
    )

    exits: list[dict[str, Any]] = []
    for row in df.itertuples(index=False):
        exits.append(
            evaluate_exit(
                price=price,
                entry_time=getattr(row, "entry_time_utc"),
                direction=getattr(row, "signal_direction"),
                entry_price=float(getattr(row, "entry_price")) if pd.notna(getattr(row, "entry_price")) else np.nan,
                hold_hours=args.hold_hours,
                tp_pct=args.tp_pct,
                sl_pct=args.sl_pct,
            )
        )
    exit_df = pd.DataFrame(exits)
    out = pd.concat([df.reset_index(drop=True), exit_df.reset_index(drop=True)], axis=1)

    out["ignore_reason"] = out.apply(lambda r: ignore_reason(r, args.flat_pct), axis=1)
    out["ignore_trade"] = (out["ignore_reason"].astype(str) != "").astype(int)
    out["potential_trade"] = (
        (out["signal_direction"].isin(["LONG", "SHORT"]))
        & (out["entry_price"].notna())
        & (out["entry_time_utc"].notna())
    ).astype(int)
    out["ml_outcome"] = np.select(
        [
            out["ignore_trade"].eq(1),
            out["signed_return_pct"].gt(0),
            out["signed_return_pct"].lt(0),
        ],
        ["IGNORE", "WIN", "LOSS"],
        default="FLAT",
    )
    return out


def main() -> None:
    args = parse_args()
    touches = pd.read_csv(args.touch_log)
    price = load_price(args.price)
    out = build_candidates(touches, price, args)

    output_csv = Path(args.output_csv)
    output_parquet = Path(args.output_parquet)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    output_parquet.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_csv, index=False)
    out.to_parquet(output_parquet, index=False)

    summary = {
        "rows": int(len(out)),
        "potential_trade": int(out["potential_trade"].sum()),
        "ignored": int(out["ignore_trade"].sum()),
        "trade_category_counts": out["trade_category"].value_counts(dropna=False).to_dict(),
        "close_action_counts": out["close_action"].value_counts(dropna=False).to_dict(),
        "ml_outcome_counts": out["ml_outcome"].value_counts(dropna=False).to_dict(),
        "output_csv": str(output_csv),
        "output_parquet": str(output_parquet),
    }
    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    main()
