from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


IST = "Asia/Kolkata"
UTC = "UTC"

HARD_ASPECTS = {"conjunction", "conjunction_orb", "square", "opposition", "opposition_orb"}
SOFT_ASPECTS = {"sextile", "trine"}
OUTER_OR_NODE_BODIES = {"RAHU", "KETU", "URANUS", "NEPTUNE", "PLUTO"}
FAST_BODIES = {"MOON", "MERCURY", "VENUS", "SUN", "MARS"}
NATURAL_PLANET_BIAS = {
    "JUPITER": 1.0,
    "VENUS": 0.8,
    "MERCURY": 0.3,
    "MOON": 0.2,
    "SUN": -0.1,
    "MARS": -0.6,
    "SATURN": -0.8,
    "RAHU": -0.7,
    "KETU": -0.5,
    "URANUS": -0.4,
    "NEPTUNE": -0.4,
    "PLUTO": -0.6,
}
NATAL_HOUSE_BIAS = {
    1: 0.4,
    2: 0.9,
    3: 0.3,
    4: 0.2,
    5: 0.8,
    6: -0.5,
    7: 0.1,
    8: -1.0,
    9: 0.8,
    10: 0.7,
    11: 1.0,
    12: -0.9,
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Build ML-ready trade candidates from aspect/SR touch rows. "
            "Each candidate is labelled as single_aspect or multiple_aspects, "
            "then evaluated with TP/SL/time-close rules."
        )
    )
    parser.add_argument(
        "--touch-log",
        default=r"C:\Users\ADMIN\Desktop\doc\sr_touch_full_1year_20260430_001906.csv",
        help="Touch CSV generated by sr_touch_lazy_dashboard.py or build_aspect_sr_touch_log.py.",
    )
    parser.add_argument(
        "--price",
        default=r"C:\Users\ADMIN\PycharmProjects\usd_jpy_h1_mt5_metaquotes_demo_full.parquet",
        help="OHLC parquet with a timezone-aware DatetimeIndex.",
    )
    parser.add_argument(
        "--output-csv",
        default=r"C:\Users\ADMIN\PycharmProjects\trade_candidates_aspect_sr_1y.csv",
        help="Output CSV path.",
    )
    parser.add_argument(
        "--output-parquet",
        default=r"C:\Users\ADMIN\PycharmProjects\trade_candidates_aspect_sr_1y.parquet",
        help="Output parquet path.",
    )
    parser.add_argument("--hold-hours", type=int, default=72)
    parser.add_argument("--tp-pct", type=float, default=0.30)
    parser.add_argument("--sl-pct", type=float, default=0.20)
    parser.add_argument(
        "--flat-pct",
        type=float,
        default=0.05,
        help="Absolute signed return below this percent is marked as low_movement for ML ignore analysis.",
    )
    return parser.parse_args()


def load_price(path: str) -> pd.DataFrame:
    price = pd.read_parquet(path).copy()
    if not isinstance(price.index, pd.DatetimeIndex):
        raise ValueError("Price parquet must have a DatetimeIndex.")
    if price.index.tz is None:
        price.index = price.index.tz_localize(UTC)
    else:
        price.index = price.index.tz_convert(UTC)
    required = {"open", "high", "low", "close"}
    missing = required - set(price.columns)
    if missing:
        raise ValueError(f"Price parquet missing columns: {sorted(missing)}")
    return price.sort_index()


def parse_event_aspect_count(value: Any) -> int:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return 0
    try:
        parsed = json.loads(str(value))
    except Exception:
        return 0
    if isinstance(parsed, list):
        return len(parsed)
    return 0


def safe_json_list(value: Any) -> list[dict[str, Any]]:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return []
    try:
        parsed = json.loads(str(value))
    except Exception:
        return []
    if not isinstance(parsed, list):
        return []
    return [item for item in parsed if isinstance(item, dict)]


def normalize_body(value: Any) -> str:
    return str(value or "").strip().upper()


def aspect_family(aspect: Any) -> str:
    name = str(aspect or "").strip().lower()
    if name in HARD_ASPECTS or name.startswith("rashi_"):
        return "hard"
    if name in SOFT_ASPECTS:
        return "soft"
    return "other"


def comparable_aspect_name(aspect: Any) -> str:
    name = str(aspect or "").strip().lower()
    if name.endswith("_orb"):
        name = name[: -len("_orb")]
    return name


def pair_bodies(pair_key: Any) -> set[str]:
    text = str(pair_key or "").strip()
    if not text:
        return set()
    return {normalize_body(part) for part in text.split("|") if str(part).strip()}


def duration_bucket(minutes: Any) -> str:
    try:
        value = float(minutes)
    except Exception:
        return "unknown"
    if not np.isfinite(value):
        return "unknown"
    if value <= 24.0 * 60.0:
        return "trigger_le_1d"
    if value <= 5.0 * 24.0 * 60.0:
        return "swing_1d_to_5d"
    return "position_gt_5d"


def body_bias(body: Any) -> float:
    return float(NATURAL_PLANET_BIAS.get(normalize_body(body), 0.0))


def house_bias(house: Any) -> float:
    try:
        key = int(float(house))
    except Exception:
        return 0.0
    return float(NATAL_HOUSE_BIAS.get(key, 0.0))


def aspect_family_bias(aspect: Any) -> float:
    family = aspect_family(aspect)
    if family == "soft":
        return 0.25
    if family == "hard":
        return -0.25
    return 0.0


def hit_strength(hit: dict[str, Any]) -> float:
    for key in ("bphs_strength", "score"):
        try:
            value = float(hit.get(key))
        except Exception:
            continue
        if np.isfinite(value):
            return max(0.0, value)
    return 0.0


def score_transit_natal_hits(
    value: Any,
    event_aspect: Any = None,
    event_bodies: set[str] | None = None,
) -> dict[str, Any]:
    hits = safe_json_list(value)
    bodies = {normalize_body(body) for body in (event_bodies or set()) if normalize_body(body)}
    aspect_name = comparable_aspect_name(event_aspect)
    if bodies:
        body_hits = [hit for hit in hits if normalize_body(hit.get("transit_planet")) in bodies]
        aspect_hits = [
            hit for hit in body_hits
            if aspect_name and comparable_aspect_name(hit.get("aspect")) == aspect_name
        ]
        hits = aspect_hits or body_hits

    bullish = 0.0
    bearish = 0.0
    strongest_id = ""
    strongest_signed = 0.0
    strongest_abs = 0.0
    scored_hits = 0

    for hit in hits:
        strength = hit_strength(hit)
        if strength <= 0:
            continue
        scored_hits += 1
        directional_bias = (
            house_bias(hit.get("natal_house"))
            + 0.50 * body_bias(hit.get("natal_planet"))
            + 0.25 * body_bias(hit.get("transit_planet"))
            + aspect_family_bias(hit.get("aspect"))
        )
        signed = strength * directional_bias
        if signed >= 0:
            bullish += signed
        else:
            bearish += abs(signed)
        if abs(signed) > strongest_abs:
            strongest_abs = abs(signed)
            strongest_signed = signed
            strongest_id = (
                f"{normalize_body(hit.get('transit_planet'))}>"
                f"{normalize_body(hit.get('natal_planet'))}:"
                f"{str(hit.get('aspect', '')).strip().lower()}"
            )

    net = bullish - bearish
    conflict = min(bullish, bearish)
    if scored_hits <= 0:
        direction = "UNKNOWN"
    elif bullish > bearish * 1.25:
        direction = "BULLISH"
    elif bearish > bullish * 1.25:
        direction = "BEARISH"
    else:
        direction = "CONFLICT"

    return {
        "jyotish_bullish_score": float(bullish),
        "jyotish_bearish_score": float(bearish),
        "jyotish_net_score": float(net),
        "jyotish_conflict_score": float(conflict),
        "jyotish_hypothesis_direction": direction,
        "jyotish_scored_hit_count": int(scored_hits),
        "dominant_aspect_id": strongest_id,
        "dominant_aspect_signed_score": float(strongest_signed),
        "dominant_aspect_abs_score": float(strongest_abs),
    }


def score_transit_natal_hits_for_row(row: pd.Series) -> dict[str, Any]:
    return score_transit_natal_hits(
        row.get("tn_hits_json"),
        event_aspect=row.get("aspect"),
        event_bodies=pair_bodies(row.get("pair_key")),
    )


def aspect_stats_from_event_json(value: Any) -> dict[str, Any]:
    aspects = safe_json_list(value)
    hard = 0
    soft = 0
    has_moon = False
    has_outer_or_node = False
    max_duration = 0.0
    for item in aspects:
        family = aspect_family(item.get("aspect"))
        hard += int(family == "hard")
        soft += int(family == "soft")
        bodies = [normalize_body(b) for b in item.get("bodies", []) if str(b or "").strip()]
        has_moon = has_moon or ("MOON" in bodies)
        has_outer_or_node = has_outer_or_node or any(body in OUTER_OR_NODE_BODIES for body in bodies)
        try:
            dur = float(item.get("duration_min"))
        except Exception:
            dur = 0.0
        if np.isfinite(dur):
            max_duration = max(max_duration, dur)

    return {
        "active_hard_aspect_count": int(hard),
        "active_soft_aspect_count": int(soft),
        "has_mixed_hard_soft_aspects": int(hard > 0 and soft > 0),
        "event_json_has_moon": int(has_moon),
        "event_json_has_outer_or_node": int(has_outer_or_node),
        "event_json_max_duration_minutes": float(max_duration),
    }


def normalize_touch_time(value: Any) -> pd.Timestamp | pd.NaT:
    ts = pd.to_datetime(value, errors="coerce")
    if pd.isna(ts):
        return pd.NaT
    if ts.tzinfo is None:
        ts = ts.tz_localize(IST)
    return ts.tz_convert(UTC)


def signal_direction(zone_kind: Any) -> str:
    zone = str(zone_kind or "").strip().lower()
    if zone == "bullish":
        return "LONG"
    if zone == "bearish":
        return "SHORT"
    return "NONE"


def signed_return_pct(direction: str, entry: float, close: float) -> float:
    if not np.isfinite(entry) or entry <= 0 or not np.isfinite(close):
        return np.nan
    raw = (float(close) - float(entry)) / float(entry) * 100.0
    if direction == "SHORT":
        return -raw
    if direction == "LONG":
        return raw
    return np.nan


def evaluate_exit(
    price: pd.DataFrame,
    entry_time: pd.Timestamp,
    direction: str,
    entry_price: float,
    hold_hours: int,
    tp_pct: float,
    sl_pct: float,
) -> dict[str, Any]:
    if direction not in {"LONG", "SHORT"}:
        return {"close_action": "IGNORE", "close_reason": "missing_direction"}
    if pd.isna(entry_time) or not np.isfinite(entry_price) or entry_price <= 0:
        return {"close_action": "IGNORE", "close_reason": "missing_entry"}

    end_time = entry_time + pd.Timedelta(hours=int(hold_hours))
    future = price[(price.index > entry_time) & (price.index <= end_time)].copy()
    if future.empty:
        return {"close_action": "IGNORE", "close_reason": "no_future_data"}

    entry = float(entry_price)
    tp = entry * (1.0 + tp_pct / 100.0) if direction == "LONG" else entry * (1.0 - tp_pct / 100.0)
    sl = entry * (1.0 - sl_pct / 100.0) if direction == "LONG" else entry * (1.0 + sl_pct / 100.0)

    max_high = float(future["high"].max())
    min_low = float(future["low"].min())
    final_close = float(future["close"].iloc[-1])
    final_time = future.index[-1]

    if direction == "LONG":
        mfe = (max_high - entry) / entry * 100.0
        mae = (entry - min_low) / entry * 100.0
    else:
        mfe = (entry - min_low) / entry * 100.0
        mae = (max_high - entry) / entry * 100.0

    for ts, row in future.iterrows():
        high = float(row["high"])
        low = float(row["low"])
        if direction == "LONG":
            hit_tp = high >= tp
            hit_sl = low <= sl
        else:
            hit_tp = low <= tp
            hit_sl = high >= sl

        if hit_sl and hit_tp:
            return {
                "close_action": "STOP_LOSS",
                "close_reason": "same_bar_tp_sl_conservative",
                "close_time_utc": ts,
                "close_price": sl,
                "signed_return_pct": -float(sl_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }
        if hit_sl:
            return {
                "close_action": "STOP_LOSS",
                "close_reason": "stop_loss_first",
                "close_time_utc": ts,
                "close_price": sl,
                "signed_return_pct": -float(sl_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }
        if hit_tp:
            return {
                "close_action": "TAKE_PROFIT",
                "close_reason": "take_profit_first",
                "close_time_utc": ts,
                "close_price": tp,
                "signed_return_pct": float(tp_pct),
                "mfe_pct": float(mfe),
                "mae_pct": float(mae),
            }

    return {
        "close_action": f"TIME_CLOSE_{int(hold_hours)}H",
        "close_reason": "hold_expired",
        "close_time_utc": final_time,
        "close_price": final_close,
        "signed_return_pct": signed_return_pct(direction, entry, final_close),
        "mfe_pct": float(mfe),
        "mae_pct": float(mae),
    }


def ignore_reason(row: pd.Series, flat_pct: float) -> str:
    if row.get("signal_direction") == "NONE":
        return "missing_direction"
    if str(row.get("close_action", "")).upper() == "IGNORE":
        return str(row.get("close_reason", "ignored"))
    signed_ret = row.get("signed_return_pct")
    if pd.notna(signed_ret) and abs(float(signed_ret)) < float(flat_pct):
        return "low_movement"
    return ""


def build_candidates(touches: pd.DataFrame, price: pd.DataFrame, args: argparse.Namespace) -> pd.DataFrame:
    df = touches.copy()
    df["entry_time_utc"] = df["touch_time_local"].map(normalize_touch_time)
    df["entry_time_local"] = pd.to_datetime(df["touch_time_local"], errors="coerce")
    df["entry_price"] = pd.to_numeric(df.get("close_touch"), errors="coerce")
    df["signal_direction"] = df.get("zone_kind", "").map(signal_direction)
    df["aspect_family"] = df.get("aspect", "").map(aspect_family)
    df["duration_bucket"] = df.get("event_duration_minutes", pd.Series(index=df.index, dtype=object)).map(duration_bucket)
    df["sr_confirmation_type"] = df.get("touch_kind", "").fillna("").astype(str)
    df["sr_confirmation_score"] = df["sr_confirmation_type"].map({"confluence": 1.0, "nearest_line": 0.6}).fillna(0.0)

    active_count = pd.to_numeric(df.get("aspect_regime_active_count"), errors="coerce")
    event_json_count = df.get("event_aspects_json", pd.Series(index=df.index, dtype=object)).map(parse_event_aspect_count)
    df["active_aspect_count"] = active_count.fillna(event_json_count).fillna(0).astype(int)
    df["trade_category"] = np.where(df["active_aspect_count"] > 1, "multiple_aspects", "single_aspect")
    df["is_multiple_active"] = (df["active_aspect_count"] > 1).astype(int)
    df["has_moon_trigger"] = pd.to_numeric(df.get("touch_has_moon"), errors="coerce").fillna(0).astype(int)
    touch_planets_text = df.get("touch_planets", pd.Series(index=df.index, dtype=object)).fillna("").astype(str).str.upper()
    pair_text = df.get("pair_key", pd.Series(index=df.index, dtype=object)).fillna("").astype(str).str.upper()
    df["has_outer_or_node"] = (
        touch_planets_text.apply(lambda text: any(body in text for body in OUTER_OR_NODE_BODIES))
        | pair_text.apply(lambda text: any(body in text for body in OUTER_OR_NODE_BODIES))
    ).astype(int)

    aspect_stats = pd.DataFrame(
        df.get("event_aspects_json", pd.Series(index=df.index, dtype=object)).map(aspect_stats_from_event_json).tolist()
    )
    if not aspect_stats.empty:
        df = df.drop(columns=[col for col in aspect_stats.columns if col in df.columns], errors="ignore")
        df = pd.concat([df.reset_index(drop=True), aspect_stats.reset_index(drop=True)], axis=1)
        df["has_moon_trigger"] = np.maximum(df["has_moon_trigger"], df["event_json_has_moon"].fillna(0).astype(int))
        df["has_outer_or_node"] = np.maximum(df["has_outer_or_node"], df["event_json_has_outer_or_node"].fillna(0).astype(int))

    scored = pd.DataFrame(df.apply(score_transit_natal_hits_for_row, axis=1).tolist())
    if not scored.empty:
        df = df.drop(columns=[col for col in scored.columns if col in df.columns], errors="ignore")
        df = pd.concat([df.reset_index(drop=True), scored.reset_index(drop=True)], axis=1)
    else:
        for col in (
            "jyotish_bullish_score",
            "jyotish_bearish_score",
            "jyotish_net_score",
            "jyotish_conflict_score",
            "jyotish_scored_hit_count",
            "dominant_aspect_signed_score",
            "dominant_aspect_abs_score",
        ):
            df[col] = 0.0
        df["jyotish_hypothesis_direction"] = "UNKNOWN"
        df["dominant_aspect_id"] = ""

    event_strength = pd.to_numeric(df.get("event_bphs_strength"), errors="coerce").fillna(0.0)
    natal_strength = pd.to_numeric(df.get("tn_bphs_total"), errors="coerce").fillna(0.0)
    df["geometric_strength_score"] = event_strength
    df["natal_relevance_score"] = natal_strength
    df["rule_layer_total_strength"] = (
        df["dominant_aspect_abs_score"].fillna(0.0)
        + 0.35 * df["geometric_strength_score"]
        + 0.25 * df["sr_confirmation_score"]
    )
    df["rule_layer_conflict_ratio"] = np.where(
        (df["jyotish_bullish_score"] + df["jyotish_bearish_score"]) > 0,
        df["jyotish_conflict_score"] / (df["jyotish_bullish_score"] + df["jyotish_bearish_score"]),
        0.0,
    )
    df["rule_layer_ignore_hint"] = np.where(
        df["jyotish_hypothesis_direction"].isin(["CONFLICT", "UNKNOWN"]) | (df["rule_layer_total_strength"] < 0.25),
        1,
        0,
    )
    df["rule_layer_notes"] = (
        "heuristic_v1_yen_ipo_tokyo_1889_reference;"
        "uses_transit_natal_house_planet_nature_aspect_family_bphs_sr;"
        "ml_must_validate"
    )

    exits: list[dict[str, Any]] = []
    for row in df.itertuples(index=False):
        exits.append(
            evaluate_exit(
                price=price,
                entry_time=getattr(row, "entry_time_utc"),
                direction=getattr(row, "signal_direction"),
                entry_price=float(getattr(row, "entry_price")) if pd.notna(getattr(row, "entry_price")) else np.nan,
                hold_hours=args.hold_hours,
                tp_pct=args.tp_pct,
                sl_pct=args.sl_pct,
            )
        )
    exit_df = pd.DataFrame(exits)
    out = pd.concat([df.reset_index(drop=True), exit_df.reset_index(drop=True)], axis=1)

    out["ignore_reason"] = out.apply(lambda r: ignore_reason(r, args.flat_pct), axis=1)
    out["ignore_trade"] = (out["ignore_reason"].astype(str) != "").astype(int)
    out["potential_trade"] = (
        (out["signal_direction"].isin(["LONG", "SHORT"]))
        & (out["entry_price"].notna())
        & (out["entry_time_utc"].notna())
    ).astype(int)
    out["ml_outcome"] = np.select(
        [
            out["ignore_trade"].eq(1),
            out["signed_return_pct"].gt(0),
            out["signed_return_pct"].lt(0),
        ],
        ["IGNORE", "WIN", "LOSS"],
        default="FLAT",
    )
    return out


def main() -> None:
    args = parse_args()
    touches = pd.read_csv(args.touch_log)
    price = load_price(args.price)
    out = build_candidates(touches, price, args)

    output_csv = Path(args.output_csv)
    output_parquet = Path(args.output_parquet)
    output_csv.parent.mkdir(parents=True, exist_ok=True)
    output_parquet.parent.mkdir(parents=True, exist_ok=True)
    out.to_csv(output_csv, index=False)
    out.to_parquet(output_parquet, index=False)

    summary = {
        "rows": int(len(out)),
        "potential_trade": int(out["potential_trade"].sum()),
        "ignored": int(out["ignore_trade"].sum()),
        "trade_category_counts": out["trade_category"].value_counts(dropna=False).to_dict(),
        "close_action_counts": out["close_action"].value_counts(dropna=False).to_dict(),
        "ml_outcome_counts": out["ml_outcome"].value_counts(dropna=False).to_dict(),
        "output_csv": str(output_csv),
        "output_parquet": str(output_parquet),
    }
    print(json.dumps(summary, indent=2, default=str))


if __name__ == "__main__":
    main()
